"""1

Revision ID: dfabd3544734
Revises: 
Create Date: 2025-03-12 17:16:17.692058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfabd3544734'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('no_checked_rezume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('citi', sa.String(length=50), nullable=False),
    sa.Column('user_number', sa.String(length=60), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('progrm_lang', sa.String(length=500), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('remote_work', sa.String(length=6), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_number')
    )
    op.drop_table('check_rezume')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('login',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=400),
               existing_nullable=False)

    with op.batch_alter_table('rezume', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('citi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('user_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.alter_column('user_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('salary',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('progrm_lang',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('experience',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('remote_work',
               existing_type=sa.TEXT(),
               type_=sa.String(length=6),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['user_email'])
        batch_op.create_unique_constraint(None, ['user_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rezume', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('remote_work',
               existing_type=sa.String(length=6),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('body',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('experience',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('progrm_lang',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('salary',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_number',
               existing_type=sa.String(length=60),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('citi',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=400),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('login',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('check_rezume',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('citi', sa.TEXT(), nullable=False),
    sa.Column('user_number', sa.INTEGER(), nullable=False),
    sa.Column('user_email', sa.TEXT(), nullable=True),
    sa.Column('salary', sa.INTEGER(), nullable=True),
    sa.Column('progrm_lang', sa.TEXT(), nullable=False),
    sa.Column('experience', sa.INTEGER(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('remote_work', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('no_checked_rezume')
    # ### end Alembic commands ###
